#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p normal

# Load modules
module load eb
module load Miniconda2

# loading virtualenv
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_tmp

# demultiplexing 2017 data
split_libraries_fastq.py \
-m /home/cbmucl13/2017_03_smb/map.tsv \
-i /home/cbmucl13/2017_03_smb/Read1.fastq.gz \
-b /home/cbmucl13/2017_03_smb/Index.fastq.gz \
-o /home/cbmucl13/2017_03_smb/slout_2017 \
-q 19 \

--rev_comp_barcode \
--rev_comp_mapping_barcodes \
--barcode_type 12

source deactivate
