#!/bin/bash
#SBATCH -t 3:00:00
#SBATCH -n 24
#SBATCH -p normal

# Load modules
module load eb
module load Miniconda2

# loading virtualenv
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_tmp

# summarizing taxonomy of the merged core OTU table
summarize_taxa.py \
-i /home/cbmucl13/merged_core_table_90.biom \
-L 2 \
-o /home/cbmucl13/summarized_taxa_merged_core_otus_90

source deactivate
